"""Every op rejects a parameter it does not read, and the table saying so cannot drift.

An op takes its parameters as a dict, so without this gate an invented or misspelled name is
accepted and silently does nothing. The record renders, the digest is stable, and it is not the
record that was asked for -- which is worse than an error, because nothing anywhere says so.

The library has already paid for this once: `scope(causal=False)` was missing from that op's
forwarding list, so it rendered the causal path and hashed identically to the default.

`wfmsynth/opkeys.py` is generated by `tools/derive_op_keys.py` from the code that reads the
parameters. The first test re-runs that derivation and compares, so adding a parameter to an op
and forgetting to regenerate is a failure here rather than a rejected call in someone's script.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

import wfmsynth as ws
from wfmsynth import opkeys

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))
import derive_op_keys as derive_tool                      # noqa: E402


def test_the_committed_table_matches_what_the_code_reads():
    derived = derive_tool.derive()
    committed = opkeys.OP_KEYS
    assert set(derived) == set(committed), (
        "ops in the table and ops in the executor disagree; regenerate with "
        "`python tools/derive_op_keys.py > wfmsynth/opkeys.py`")
    drifted = {op: {"derived_only": sorted(derived[op] - committed[op]),
                    "table_only": sorted(committed[op] - derived[op])}
               for op in sorted(derived) if derived[op] != committed[op]}
    assert not drifted, (
        "the table no longer matches the code that reads the parameters. Regenerate with "
        f"`python tools/derive_op_keys.py > wfmsynth/opkeys.py`. Drift: {drifted}")


def test_every_executable_op_has_an_entry():
    from wfmsynth.compose import _EXEC
    assert set(_EXEC) == set(opkeys.OP_KEYS)


def test_no_op_claims_a_key_in_the_reserved_namespace():
    """A recipe op is flat, so `op` and the underscore prefix are structure and everything else is
    a parameter. An op accepting a key from the reserved namespace would make that rule a lie."""
    for op, keys in opkeys.OP_KEYS.items():
        assert not [k for k in keys if k.startswith("_")], op
    assert "op" not in opkeys.OP_KEYS.get("lossy", ())


def _grid():
    return ws.Grid(fs=64e9, baud=16e9, n=4096, v_full=0.8)


def _sig():
    return ws.Signal(seed=1, grid=_grid()).carrier("nrz", pattern="prbs7", n_ui=1024, tr_frac=0.35)


# the two mistakes that prompted the gate, each a plausible name for a real parameter
@pytest.mark.parametrize("call, bad", [
    (lambda s: s.sample_clock(fs_hz=256e9), "fs_hz"),      # the rate is set by n_out
    (lambda s: s.events("glitch", at_ui=512), "at_ui"),    # placement is indices=
    (lambda s: s.lossy(loss_dB=12.0), "loss_dB"),          # case matters
    (lambda s: s.scope(bandwidth_hz=33e9), "bandwidth_hz"),
])
def test_a_parameter_the_op_does_not_read_is_refused(call, bad):
    with pytest.raises(TypeError) as e:
        call(_sig())
    assert bad in str(e.value)


def test_the_message_names_the_valid_keys_and_the_nearest_match():
    with pytest.raises(TypeError) as e:
        _sig().sample_clock(ppmm=55.0)
    msg = str(e.value)
    assert "ppmm" in msg
    assert "did you mean 'ppm'" in msg          # the nearest match, so the fix is obvious
    assert "n_out" in msg and "drift_ppm_per_s" in msg     # and the whole accepted set


def test_annotations_and_structure_pass_through():
    s = _sig().lossy(loss_db=12.0).annotate(stage="channel", impairment="loss")
    assert s.ops[-1]["_prov"] == {"stage": "channel", "impairment": "loss"}
    assert ws.Signal.from_recipe(s.recipe()).sha256() == s.sha256()


def test_a_recipe_carrying_a_dead_parameter_is_refused_on_replay():
    """`from_recipe` assigns the op list directly, so it needs the same gate as the builders."""
    r = _sig().lossy(loss_db=12.0).recipe()
    r["ops"][-1]["loss_dB"] = 99.0             # a plausible-looking duplicate in the wrong case
    with pytest.raises(TypeError) as e:
        ws.Signal.from_recipe(r)
    assert "loss_dB" in str(e.value)


def test_an_unknown_op_is_left_to_the_executor_to_report():
    """The gate speaks about parameters. An op nobody can execute is compose's error to give, with
    the list of what it can run, so this must not pre-empt it with a worse message."""
    opkeys.check("not_an_op", {"whatever": 1})
