"""Derive each op's accepted parameter names from the code that reads them.

`wfmsynth/opkeys.py` is generated by this module so that the accepted set and the code that
consumes it cannot drift apart. `tests/test_op_keys.py` re-runs the derivation and asserts the
committed table still matches, so adding a parameter to an op and forgetting the table is a test
failure rather than a rejected call in someone else's script.

Every op reads its parameters in one of a few shapes, and all of them are scannable:

    p.get("name")                         a direct read, with a default
    p["name"]                             a direct read, required
    {k: p[k] for k in ("a", "b") if k in p}   the whitelist idiom, used where an op forwards to a
                                          physics function
    "name" in p                           a presence test

Two ops delegate wholesale instead, and get their sets from the callee: `carrier` builds through
`compose._carrier`, and `events` passes through to `events.place_events`, whose surplus keyword
arguments are stored on each event and later read by `apply_events` as `ev.params[...]`.
"""
from __future__ import annotations

import inspect
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PKG = REPO / "wfmsynth"
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))


def _body(name: str, text: str) -> str:
    # `):[^\n]*\n` and not `):\n` -- several ops carry a trailing comment on the def line, and
    # a pattern that insists the colon ends the line silently matches a LATER function instead,
    # so the op gets scanned against somebody else's body.
    m = re.search(rf"\ndef {name}\(.*?\):[^\n]*\n(.*?)(?=\ndef |\n_EXEC|\nclass )", text, re.S)
    return m.group(1) if m else ""


def _keys_in(body: str) -> set[str]:
    ks = set(re.findall(r'p\.get\(\s*["\']([A-Za-z_]\w*)["\']', body))
    ks |= set(re.findall(r'p\[\s*["\']([A-Za-z_]\w*)["\']\s*\]', body))
    # the whitelist idiom, in both the comprehension form and the multi-line loop form
    for tup in re.findall(r"for k in \(([^)]*)\)\s*(?::\s*\n\s*)?if k in p", body, re.S):
        ks |= set(re.findall(r'["\']([A-Za-z_]\w*)["\']', tup))
    ks |= set(re.findall(r'["\']([A-Za-z_]\w*)["\']\s*in p\b', body))
    return ks


def _param_helpers(text: str) -> dict[str, str]:
    """Module-level helpers that take the parameter dict, by name -> body.

    An op often reads nothing itself and hands `p` to one of these, so the keys it accepts are
    theirs. `symbols` is the clearest case: every key naming a symbol source is read inside
    `_source_symbols`, not in the op.
    """
    out = {}
    for m in re.finditer(r"\ndef (_[a-z_0-9]+)\(([^)]*)\):\n", text):
        name, args = m.group(1), m.group(2)
        if re.search(r"\bp\b|\bspec\b", args):
            out[name] = _body(name, text)
    return out


def _module_key_tuples(body: str) -> set[str]:
    """Keys named by a module-level tuple constant the body iterates.

    Some ops keep their accepted set in a named constant (`_MULTIPAIR_KEYS`) rather than an inline
    tuple, so the value has to come from the module rather than from the text.
    """
    from wfmsynth import compose as C
    ks: set[str] = set()
    for name in re.findall(r"\b(_[A-Z][A-Z_0-9]*)\b", body):
        val = getattr(C, name, None)
        if isinstance(val, (tuple, list, set, frozenset)) and all(isinstance(v, str) for v in val):
            ks |= set(val)
    return ks


def _keys_deep(body: str, helpers: dict[str, str], seen=None) -> set[str]:
    """Keys read by this body and by any parameter-reading helper it calls."""
    seen = set() if seen is None else seen
    ks = _keys_in(body) | _module_key_tuples(body)
    for name, hbody in helpers.items():
        if name in seen or not re.search(rf"\b{name}\(", body):
            continue
        seen.add(name)
        ks |= _keys_deep(hbody, helpers, seen)
    return ks


def derive() -> dict[str, frozenset[str]]:
    """op name -> the parameter names that op actually reads."""
    from wfmsynth import compose as C
    from wfmsynth.events import place_events

    compose_src = (PKG / "compose.py").read_text()
    events_src = (PKG / "events.py").read_text()

    mech = set(re.findall(r'ev\.params\.get\(\s*["\']([A-Za-z_]\w*)["\']', events_src))
    mech |= set(re.findall(r'ev\.params\[\s*["\']([A-Za-z_]\w*)["\']\s*\]', events_src))
    placement = {p for p in inspect.signature(place_events).parameters
                 if p not in ("n", "grid", "rng", "x", "params")}
    helpers = _param_helpers(compose_src)
    table: dict[str, frozenset[str]] = {}
    for op, fn in C._EXEC.items():
        ks = _keys_deep(_body(fn.__name__, compose_src), helpers)
        if op == "events":
            # `events` hands its surplus keywords to `place_events`, which stores them on each
            # event for `apply_events` to read, so the set spans two modules.
            ks |= placement | mech
        table[op] = frozenset(k for k in ks if not k.startswith("_"))
    return table


def render() -> str:
    table = derive()
    out = ['"""The parameter names each op accepts. GENERATED -- see tools/derive_op_keys.py.',
           "",
           "Regenerate with:  python tools/derive_op_keys.py > wfmsynth/opkeys.py",
           '"""',
           "from __future__ import annotations",
           "",
           "import difflib",
           "import os",
           "",
           "# Keys that are structure rather than parameters. Anything else beginning with an",
           "# underscore is the annotation namespace and is also allowed through.",
           'STRUCTURAL = frozenset({"op"})',
           "",
           "OP_KEYS = {"]
    for op in sorted(table):
        ks = ", ".join(f'"{k}"' for k in sorted(table[op]))
        out.append(f'    "{op}": frozenset({{{ks}}}),')
    out += ["}", "", "", CHECK_SRC]
    return "\n".join(out) + "\n"


CHECK_SRC = '''def check(op, params):
    """Raise on a parameter this op does not read.

    Ops take their parameters as a dict, so without this an invented or misspelled name is
    accepted and silently does nothing: the record renders, the digest is stable, and it is not
    the record that was asked for. `scope(causal=False)` was once exactly this -- the flag was
    missing from the op's forwarding list, so it rendered the causal path and hashed identically
    to the default.

    Unknown ops are left alone; `compose` reports those with the list of what it can execute.
    """
    if op not in OP_KEYS:
        return
    allowed = OP_KEYS[op]
    unknown = [k for k in params
               if k not in allowed and k not in STRUCTURAL and not k.startswith("_")]
    if not unknown:
        return
    audit = os.environ.get("WFMSYNTH_OPKEY_AUDIT")
    if audit:
        # Maintenance hook. Set the variable to a path and run the suite to collect every key the
        # real code passes that this table lacks, instead of failing on the first one. That is how
        # the table is repaired after an op learns a parameter the derivation cannot see.
        with open(audit, "a") as fh:
            for k in sorted(unknown):
                fh.write(f"{op}" + chr(9) + f"{k}" + chr(10))
        return
    lines = []
    for k in sorted(unknown):
        near = difflib.get_close_matches(k, sorted(allowed), n=2, cutoff=0.6)
        lines.append(f"  {k!r}" + (f" -- did you mean {' or '.join(repr(n) for n in near)}?"
                                   if near else ""))
    raise TypeError(
        f"op {op!r} does not take " + ", ".join(repr(k) for k in sorted(unknown)) + ".\\n"
        + "\\n".join(lines)
        + f"\\n  {op!r} takes: " + ", ".join(sorted(allowed))
        + "\\nA parameter an op does not read would be recorded in the recipe and change nothing.")
'''


if __name__ == "__main__":
    print(render(), end="")
